export default {
  FETCH_TODOS_START: '[redux 2] FETCH_TODOS_START',
  FETCH_TODOS_SUCCESS: '[redux 2] FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: '[redux 2] FETCH_TODOS_FAILURE',
  SET_TODO_PAGE: '[redux 2] SET_TODO_PAGE',
} as const
